### PR TITLE
Added acknowledged column for the hostgroups_detail method

### PR DESCRIPTION
**Pull request by fgimian**
Hey there, great library!

I've just added the ability to detect if a host issue has been acknowledged or not for the hostgroups_detail method.  This is really useful for our dashboards (which are written with dashing).

Cheers
Fotis

### CODE REVIEW

**Comment by fgimian** [comment]
Hi there, was just wondering if you've had a chance to consider my pull request?

Thanks a lot!
Fotis

**Comment by fgimian** [comment]
Hey there, I was wondering if you had a chance to check this out? :smile:

**Comment by Celant** [comment]
+1 this works and is exactly what I needed. @railsmachine-ops I highly suggest this gets merged.

**Comment by luc-tielen** [comment]
Any update on this? We would also like to have this feature for our dashboards..

**Comment by luc-tielen** [comment]
Thanks for merging in! Already using it in our dashboards! 😊

**Pull request merged**
